
= ocaml_ns_config
:page-permalink: /:path/ocaml_ns_config
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: refman
:page-sidebar: rules_ocaml_refman_sbdata
:page-parent: ['../reference']
:page-tags: [tools,ocaml]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Mar 18, 2025

`load("@rules_ocaml//build:rules.bzl", "ocaml_ns_config")`

[.prototype]
pass:[
ocaml_ns_config(<a href="#ocaml_ns_config-name">name</a>, <a href="#ocaml_ns_config-env">env</a>, <a href="#ocaml_ns_config-import_as">import_as</a>, <a href="#ocaml_ns_config-ns_import_as">ns_import_as</a>, <a href="#ocaml_ns_config-ns_merge">ns_merge</a>, <a href="#ocaml_ns_config-ns_name">ns_name</a>, <a href="#ocaml_ns_config-opts">opts</a>, <a href="#ocaml_ns_config-private">private</a>, <a href="#ocaml_ns_config-submodules">submodules</a>)
]

OBSOLETE DOCSTRING!  under revision...

This rule initializes a 'namespace evaluation environment' consisting of a pseudo-namespace prefix string and optionally an ns resolver module.  A pseudo-namespace prefix string is a string that is used to form (by prefixation) a (presumably) globally unique name for a module. An ns resolver module is a module that contains nothing but alias equations mapping module names to pseudo-namespaced module names.

This rule is designed to work in conjujnction with rules
[ocaml_module](rules_ocaml.md#ocaml_module) and
[ocaml_ns_module](rules_ocaml.md#ocaml_ns_module). An `ocaml_module`
instance can use the prefix string of an `ppx_ns` to rename its
source file by using attribute `ns` to reference the label of an
`ppx_ns` target. Instances of `ocaml_ns_module` can list such
modules as `submodule` dependencies. They can also use an
`ppx_ns` prefix string to name themselves, by using their `ns`
attribute similarly. This allows ns modules to be (pseudo-)namespaced in the
same way submodules are namespaced.

The prefix string defaults to the (Bazel) package name string, with
each segment capitalized and the path separator ('/') replaced by the
`sep` string (default: `_`). If you pass a prefix string it must be a
legal OCaml module path; each segment will be capitalized and the segment
separator ('.') will be replaced by the `sep` string. The resulting
prefix may be used by `ocaml_module` rules (via the `ns` attribute) to
rename their source files, and, if `module = True`, by this rule to
generate alias equations.

For example, if package `//alpha/beta/gamma` contains`foo.ml`:

```
ns_config() => Alpha_Beta_Gamma__foo.ml
ns_config(sep="") => AlphaBetaGamma__foo.ml
ns_config(sep="__") => Alpha__Beta__Gamma__foo.ml
ns_config(prefix="foo.bar") => Foo_Bar__foo.ml (pkg path ignored)
ns_config(prefix="foo.bar", sep="") => FooBar__foo.ml
```

The optional ns resolver module will be named `<prefix>__00.ml`; since
`0` is not a legal initial character for an OCaml module name, this
ensures it will never clash with a user-defined module.

The ns resolver module will contain alias equations mapping module
names derived from the `srcs` list to pseudo-namespaced module names
(and thus indirectly filenames). For example, if `srcs` contains
`foo.ml`, and the prefix is `a.b`, then the resolver module will
contain `module Foo = A_b_foo`.

Submodule file names will be formed by prefixing the pseudo-ns prefix to the (original, un-namespaced) module name, separated by 'sep' (default: '__'). For example, if the prefix is 'Foo_bar' and the module is 'baz.ml', the submodule file name will be 'Foo_bar__baz.ml'.

The main namespace module will contain aliasing equations that map module names to these prefixed module names.

By default, the ns prefix string is formed from the package name, with '/' replaced by '_'. You can use the 'ns' attribute to change this:

ns(ns = "foobar", srcs = glob(["*.ml"]))


== Attributes

[.rule_attrs]
[cols="1,3,1,1,1"]
|===
| Name  | Description | Type | Mandatory | Default

| +++<a class="rule-attr" id="ocaml_ns_config-name"></a>+++name
|  A unique name for this target. | +++<a href="https://bazel.build/concepts/labels#target-names">Name</a>+++
| required
| 
| +++<a class="rule-attr" id="ocaml_ns_config-env"></a>+++env
|  Env variables | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: String -> String</a>+++
| optional
| {}
| +++<a class="rule-attr" id="ocaml_ns_config-import_as"></a>+++import_as
|  Exogenous (sub)modules, namespaced or non-namespaced.  Aliased names will not be prefixed with ns name of this ns_config.

Keys: labels of modules;
Values: alias name to be used in this resolver.

e.g. '//mwe/rgb:R': 'Red' will generate

module R = Red | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: Label -> String</a>+++
| optional
| {}
| +++<a class="rule-attr" id="ocaml_ns_config-ns_import_as"></a>+++ns_import_as
|  Dictionary: keys are exogenous namespaces (resolver modules),
values are strings to serve as ns name aliases.
Example: {"//foo/bar:nsbaz": "FOOBARBAZ"} | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: Label -> String</a>+++
| optional
| {}
| +++<a class="rule-attr" id="ocaml_ns_config-ns_merge"></a>+++ns_merge
|  Merges all submodules of an exogenous namespace. | +++<a href="https://bazel.build/concepts/labels">List of labels</a>+++
| optional
| []
| +++<a class="rule-attr" id="ocaml_ns_config-ns_name"></a>+++ns_name
|  Use this as the ns name (prefix string) | +++String+++
| optional
| ""
| +++<a class="rule-attr" id="ocaml_ns_config-opts"></a>+++opts
|  List of compile options; overrides configurable default options. Supports `+-no-+` prefix for each option; for example, `-no-linkall`. | +++List of strings+++
| optional
| []
| +++<a class="rule-attr" id="ocaml_ns_config-private"></a>+++private
|  If True, suffix '__0' to the ns name, to make it quasi-private. Not to be confused with the standard Bazel 'visibility' attribute.

Set this to True if you have a module whose name matches the ns name. | +++Boolean+++
| optional
| False
| +++<a class="rule-attr" id="ocaml_ns_config-submodules"></a>+++submodules
|  List of strings from which submodule names are to be derived for aliasing. Bazel labels may be used; the submodule name will be derived from the target part. For example, '//a/b:c' normalizes to C. But they are just strings, and will not be checked against any files.

The normalized submodule names must match the names of the modules electing membership via the 'ns_config' attribute. | +++List of strings+++
| optional
| []

|===



