
= ocaml_ns_config
:page-permalink: /:path/ocaml_ns_config
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: refman
:page-sidebar: rules_ocaml_refman_sbdata
:page-parent: ['../reference']
:page-tags: [tools,ocaml]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Mar 27, 2025

`load("@rules_ocaml//build:rules.bzl", "ocaml_ns_config")`

[.prototype]
pass:[
ocaml_ns_config(<a href="#ocaml_ns_config-name">name</a>, <a href="#ocaml_ns_config-env">env</a>, <a href="#ocaml_ns_config-import_as">import_as</a>, <a href="#ocaml_ns_config-ns_import_as">ns_import_as</a>, <a href="#ocaml_ns_config-ns_merge">ns_merge</a>, <a href="#ocaml_ns_config-ns_name">ns_name</a>, <a href="#ocaml_ns_config-opts">opts</a>, <a href="#ocaml_ns_config-private">private</a>, <a href="#ocaml_ns_config-submodules">submodules</a>)
]

Generates a source `<ns>.ml` file containing the module aliasing equations needed to define an OCaml build namespace.


== Attributes

[.rule_attrs]
[cols="1,4,2,1,1"]
|===
| Name  | Description | Type | Mandatory | Default

| [[_ocaml_ns_config_name]]name
|  A unique name for this target. | +++<a href="https://bazel.build/concepts/labels#target-names">Name</a>+++
| required
| 
| [[_ocaml_ns_config_env]]env
|  Env variables | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: String -> String</a>+++
| optional
| {}
| [[_ocaml_ns_config_import_as]]import_as
|  Import exogenous (non-namepaced) modules.

Exogenous (sub)modules, namespaced or non-namespaced.  Aliased names will not be prefixed with ns name of this ns_config.

Keys: labels of modules;
Values: alias name to be used in this resolver.

e.g. `import_as = {"//mwe/rgb:R": "Red"}` will generate

module R = Red | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: Label -> String</a>+++
| optional
| {}
| [[_ocaml_ns_config_ns_import_as]]ns_import_as
|  Import exogenous namespaces (`ocaml_ns` targets).

Dictionary: keys are exogenous namespaces (`ocaml_ns` modules),
values are strings to serve as ns name aliases.
Example: {"//foo/bar:nsbaz": "FBB"} | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: Label -> String</a>+++
| optional
| {}
| [[_ocaml_ns_config_ns_merge]]ns_merge
|  Merges all submodules of an exogenous namespace. | +++<a href="https://bazel.build/concepts/labels">List of labels</a>+++
| optional
| []
| [[_ocaml_ns_config_ns_name]]ns_name
|  Use this as the ns name (prefix string) | +++String+++
| optional
| ""
| [[_ocaml_ns_config_opts]]opts
|  List of compile options; overrides configurable default options. Supports `+-no-+` prefix for each option; for example, `-no-linkall`. | +++List of strings+++
| optional
| []
| [[_ocaml_ns_config_private]]private
|  When True, adds suffix `+__+` to ns name. Use this option when you have a module whose name matches the ns name. Such a module will function as the ns resolver, and may export only a subset of the members of the namespace.

Not to be confused with the https://bazel.build/concepts/visibility[visibility,window=_blank] attribute, which controls visibility of the target within the Bazel environment. | +++Boolean+++
| optional
| False
| [[_ocaml_ns_config_submodules]]submodules
|  List of strings from which submodule names are to be derived for aliasing. Bazel labels may be used; the submodule name will be derived from the target part. For example, '//a/b:c' normalizes to C. But they are just strings, and will not be checked against any files.

The normalized submodule names must match the names of the modules electing membership via the 'ns_config' attribute. | +++List of strings+++
| optional
| []

|===



