
= ocaml_library
:page-permalink: /:path/ocaml_library
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: refman
:page-sidebar: rules_ocaml_refman_sbdata
:page-parent: ['../reference']
:page-tags: [tools,ocaml]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Mar 27, 2025

`load("@rules_ocaml//build/_rules:ocaml_library.bzl", "ocaml_library")`

[.prototype]
pass:[
ocaml_library(<a href="#ocaml_library-name">name</a>, <a href="#ocaml_library-archive_name">archive_name</a>, <a href="#ocaml_library-env">env</a>, <a href="#ocaml_library-linkage">linkage</a>, <a href="#ocaml_library-manifest">manifest</a>, <a href="#ocaml_library-opts">opts</a>)
]

Aggregates a collection of OCaml modules.

An `ocaml_library` is a collection of modules packaged into an OBazl
target; it is not a single binary file. It is an OBazl convenience rule
that allows a target to depend on a collection of deps under a single
label, rather than having to list each individually.

By default, libraries are not archived unless the client explicitly requests archiving.  If you build a library directly from the command line, you'll get an archive.  But if a rule depends on an `ocaml_library` target, no archive will be produced. This default policy can be overridden. For example, an `ocaml_binary` target can set `force_archived_libdeps` to True.

WARNING: This feature - context-dependent archiving - is still under development.


== Attributes

[.rule_attrs]
[cols="1,4,2,1,1"]
|===
| Name  | Description | Type | Mandatory | Default

| [[_ocaml_library_name]]name
|  A unique name for this target. | +++<a href="https://bazel.build/concepts/labels#target-names">Name</a>+++
| required
| 
| [[_ocaml_library_archive_name]]archive_name
|  Name of generated archive file, without extension. If not provided, name will be derived from target 'name' attribute. | +++String+++
| optional
| ""
| [[_ocaml_library_env]]env
|  Env variables | +++<a href="https://bazel.build/rules/lib/dict">Dictionary: String -> String</a>+++
| optional
| {}
| [[_ocaml_library_linkage]]linkage
|  By default, libraries are not packaged as archives or cmxs files.
"static": archive the library; "shared": build cmxs. | +++String+++
| optional
| ""
| [[_ocaml_library_manifest]]manifest
|  List of component modules for libraries. | +++<a href="https://bazel.build/concepts/labels">List of labels</a>+++
| optional
| []
| [[_ocaml_library_opts]]opts
|  List of compile options; overrides configurable default options. Supports `+-no-+` prefix for each option; for example, `-no-linkall`. | +++List of strings+++
| optional
| []

|===



