= Dependencies
:page-permalink: /:path/opam-dependencies
:page-layout: page_tools_opam
:page-pkg: tools_opam
:page-doc: dg
:page-sidebar: tools_opam_dg_sbdata
:page-parent: ['../dev-guide']
:page-tags: [opam,tools,dependencies]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: May 15, 2022
:toc-title:
:toc: true

== The Build Environment

The _build environment_ is analogous to the evaluation environment
used by compilers. The evaluation environment is usually implemented
as a symbol table of some kind (or more likely, a stack of such tables
representing nested environments) that maps symbols to values.

Compilers usually need some assistance to manage such environments.
When compiling a particular compilation unit (i.e. source file), they
may need to resolve symbols that are defined in separately compiled
modules. Most compilers maintain a list of file system paths that they
will search for the resources (modules) they need to resolve symbols.
The initial list is minimal, containing only the directories
containing the language kernel modules and perhaps a standard library.
This is the initial build environment. Compilers also support some
mechanism that allows the (meta-)programmer to designate a list of
directories to add to the list - for OCaml, this is the `-I` compile
option.

To compile a source file, the initial environment (search list) must
be elaborated to expose the resources needed to resolve all symbols in
the source file. This requires a kind of meta-programming. At a
minimum, the programmer might write a Make file or even just a shell
script that explicitly lists, for each build target, the directories
containing the modules it depends on. More commonly, developers use a
build tool like Dune or OBazl that makes it easier to express
dependencies and automatically generates a compile command including
the appropriate `-I` arguments.

A goal of OBazl is to minimize the amount of work required to get the
dependencies right. Ideally, this could be entirely automated: a
single command would generate the correct dependency expression for
each build target.

In practice, unassisted generation of dependency expressions is not
possible for OCaml. Source files alone do not contain sufficient
information to resolve all dependencies. This is mainly due to lack of
a standard mapping from OCaml namespaces to the file system, and the
simple fact that the build environment depends on the compiler
command. For example, it is not unusual for a source file to refer to
symbols that are defined in a module that must be added to the build
environment by passing an `-open` argument to the compiler. In such
cases nothing in the source file indicates how such symbols must be
resolved; that information must be provided by meta-programming - i.e.
constructing the correct compile command.

Another common case involves the use of what Dune calls "wrapped"
libraries. The build environment for such libraries includes a module
generated by the build tool, which cannot be determined from the
information in the source files alone.

== Automating dependency expressions

* Each source file has an implicit build environment: a mapping from
  module names (deps) to files.
* A complete build environment is sufficient for generation of build command lines.
* Given the build environment, generate OBazl dependency expressions (of form `deps = ["A", "B", ...]`)

From a build perspective, there are two kinds of modules, static and
dynamic. Statically determined modules are composed of source files;
that is, their sources are not generated during the build process.
Dynamically configured modules are modules whose source files are
generated.

Examples of dynamically configured modules:

* `ns_resolver` modules generated for automatically managed namespaces ("wrapped libraries")
* modules whose sources are generated by standard tools like `ocamllex`, `ocamlyacc`, `menhir`, etc.
* source files generated by shell scripts based on data from a configuration file
* sources generated by a template engine from template and data files
* etc.

A third kind: external/opam modules? Dune makes no (syntactic)
distinction between "internal" and "external" deps - you cannot tell
by reading the `libraries` field which deps are provided by OPAM
packages, for example. Why does it matter? The build env we construct
based solely on our project sources (including dune files) will be
insufficient for resolving e.g. opam deps. I.e. we'll have a list of
the modules in the project itself, but some project modules will
depend on externally-defined modules. So to resolve those, we need to
further elaborate the build env. And to do that we need help - the dev
must provide us one way or another with a list of external deps. This
can be extracted from dune and opam files; for other cases we will
need to come up with a method.




Tasks:

* find the (module) deps for for each source file - tools like `codept` and `ocamldeps` can do this

=== Constructing the deps environment


The OBazl depsenv is layered:

* Modules - struct and sig files
* Aggregates - namespaced or not; in dune, always archived
** deps:  list of local modules and workspaces (external modules)
* Bazel Packages - corresponding to dune file
** manifest: list of modules (these are not deps; packages do not have deps)
* Bazel Workspaces - list, including externals
** deps: list of workspaces, corresponds to "depends:" field of opam file
* Initial - kernel/runtime, stdlib, etc.

Dep resolution: target's deps are expressed as modules. Search order:

1.  Local package, looking for sibling
2. Aggregate deps, if target is member of an aggregate. For dune
    library stanzas, all submod deps should be resolvable by now,
    including externals, since the `libraries` field of the library
    stanza includes opam (workspace) deps.
3.  Remaining packages in workspace
4.  Workspace deps


For each source file we have a list of module dependencies (that is,
module name symbols), generated by `codept` or the like. The task is
to _resolve_ such module names - map them to the build targets that
generate the named modules, so that OBazl can construct the correct
build environment (i.e. command string) for compilation.

To do this we need to construct a build environment (for short, a `benv`) mapping module
names to build targets. It must include all module names listed as
source file depenencies.

Step one is to initialize the `benv` with all the
statically-determined modules in the project. This is easily done by
crawling the source tree to find source files, normalizing their
module names, and pairing `.ml` and `.mli` files.  Entries in the
initial benv have something like the following form:

```
Module
  name: Amod
  type: static
  sigfile:  path/to/amod.mli       # paths relative to workspace root
  structfile: path/to/amod.ml
```

The more difficult task is to add the dynamically-configured modules.
This can be broken down into several conceptually distinct tasks
corresponding to the various kinds of dynamic module.

* `ns_resolver` modules. These are the "mapping" modules, containing
  aliasing equations like `module B = Foo_b`, that are generated as
  part of the build process. Most commonly Dune is used for this, but
  it is not required. For example, the makefile-based build system for
  the OCaml toolchain uses `awk` to transform `stdlib.ml[i]`,
  rewriting lines like `module Seq = Seq` to `module Seq =
  Stdlib__seq`.

If Dune is used, we can analyze the `dune` file to extract the
information we need to elaborate the build environment. Entries for
ns_resolver modules will have the following form:

```
Module
  name: Mylib
  type: resolver
  submodules:  list of modules
```

Note that this will allow us to determine, for any given module, which
namespace it belongs to, if any.

Modules generated by ocamllex etc.:

```
Module
  name:  Mylex
  type: dynamic
  ## usually one of these, but both possible
  sigfile:  mylex.mli       ## no path for generated files, bazel figures it out
  structfile: mylex.ml
  dep:  mylex.mll
```

The sigfile/structfile info should be derivable from the dune file; if not, the tool will try to infer.

Other:

```
Module
  name:  Mygenmod
  type: dynamic
  structfile:  mygenmod.ml
```

In this case dune tells us that this is a generated file; the code
that generates it is handled separately (see below). All that's needed
for the depsenv is resolution of a module name to a build target (the
tool will generated a target that compiles the generated file.)




==== Lower levels

An "aggregate" corresponds to a Dune "library" stanza.

```
Aggregate:
  name:  Mylib
  type: archive  # dune 'library' always means archive
  ns: myns    # False for "unwrapped" libs
  opts:  list of flags etc. from dune file, applicable to all submodules
  submodules: list of modules, including dynamic ones
```

```
Package
  path:  path/to/pkg  ## relative to workspace root
  manifest: list of aggregates and modules in package
```

Workspaces: each opam file corresponds to a workspace. Dune has a
concept of "package" that may (or may not, undecided) correspond to workspace.

The tricky bit is that opam files are often not located in the root of
the workspace they determine. An OPAM distribution unit may contain
multiple opam packages (opam files); the recommendation is that they
all be placed at the root directory, named <pkg>.opam. But the sources
for a given package may be anywhere in the source tree, making it
tricky to determine which subdirectories correspond to which opam
package, and where to locate the WORKSPACE file.

For example: the `angstrom` distribution contains four opam packages.
Here's an abbreviated view of its structure:

```
angstrom.0.15.0
...
├── angstrom-async.opam
├── angstrom-lwt-unix.opam
├── angstrom-unix.opam
├── angstrom.opam
├── async
│   ├── angstrom_async.ml
│   ├── angstrom_async.mli
│   └── dune
├── benchmarks
│   ├── async_benchmark.ml
  ...
│   ├── dune
    ...
│   └── pure_benchmark.ml
├── dune-project
├── examples
│   ├── dune
│   ├── rFC2616.ml
│   └── rFC7159.ml
├── lib
│   ├── angstrom.ml
    ...
│   ├── dune
    ...
│   └── parser.ml
├── lib_test
│   ├── dune
    ...
│   └── test_let_syntax_ppx.ml
├── lwt
│   ├── angstrom_lwt_unix.ml
│   ├── angstrom_lwt_unix.mli
│   └── dune
└── unix
    ├── angstrom_unix.ml
    ├── angstrom_unix.mli
    └── dune
```

IMPORTANT: The opam package names (<pkg>.opam) do _not_ necessarily
correspond to source subdirectories! As you can see in this example:
`angstrom-lwt-unix.opam` is the opam file for the sources in `lwt`.

To make the connection between opam package name and sources, you must
read the dune file. In this case, `lwt/dune` has this to say:

```
(library
 (name angstrom_lwt_unix)
 (public_name angstrom-lwt-unix)
 ...
```

The dune `public_name` matches the opam package name. So to find the
directory for an opam package, we need to inspect all the dune files,
looking for a matching `public_name`. This includes the "main" opam
package, in this case `angstrom`, whose matching dune `library` is
defined in `lib/dune`.

IMPORTANT: In this case, the opam package name matches a `library`
stanza. I don't know if that is always the case, but it suggests that
"opam package" always means "ocaml archive", as opposed to "collection
of modules and/or archives." In principle, at least, an opam package
could contain lots of stuff. A build target could depend on such a
package, while the sources-to-build might depend on only a module
contained in the package.

This example also demonstrates a related difficulty, which is the
relation between Dune's `public_name` and `name` fields. The
`public_name` is the name of the _package_, and can be used in a build
program. But source code cannot not use it, since it is neither a
module nor an archive name. So source code will refer to the `name`
name, which does name an OCaml artifact - an archive file in this
case.

So we end up in a situation where our dependency analysis shows a
dependency on a module name like `angstrom_lwt_unix`, and to resolve
it we have to crawl around dune and opam files looking at the various
names. (In most cases, the same name is used for opam package and dune
`name` and `public_name`.)

NOTE: Dune can generate <pkg>.opam files from `dune-project` files. So
presumably the latter come first in that case. But it isn't always the
case; for example the angstrom pkg does not generate opam files from
`dune-project`. So it would not suffice to depend on dune-project
files for info.

Getting the opam/dune/workspace stuff right is critical, because in
addition to defining search spaces, they define scopes for resolution.
Each opam package lists its dependencies (which are _ipso facto_ opam
packages) and this list determines the search constraints when a dep
cannot be resolved internally, by one of the modules in its own package.

So: first read opam files, then read dune files, then reconcile.


Note there is overlap between Dune's `libraries` field, which lists
the deps of a `library` (that is, of all submodules in the library),
and opam's `depends` field, which lists all of the external deps
needed by anything in the (opam) package. In particular, the external
deps listed in a Dune `library` clause should always be a subset of
the opam `depends` list.

```
Workspace
  name:  myworkspace
  deps:  list of workspaces
```


==== Dune packages

To complicate things, we have `dune-project`,  `dune-package`, a dune `package` attribute, etc.

We also have dune "installation". The `public_name` of a library:

"(public_name <name>) this is the name under which the library can be
referred to as a dependency when it is not part of the current
workspace, i.e. when it is installed. Without a (public_name ...)
field, the library will not be installed by dune." https://dune.readthedocs.io/en/stable/dune-files.html#library

The `package` field of the library stanza:

"(package <package>) Install private library under the specified
package. Such a library is now usable by public libraries defined in
the same project. The findlib name for this library will be
<package>.__private__.<name>, however the library’s interface will be
hidden from consumers outside the project." https://dune.readthedocs.io/en/stable/dune-files.html#library

And `dune-project`: "used to mark the root of projects as well as
define project-wide parameters." Can contain multiple packages,
declared with a `package` stanza. The `generate_opam_files` field does
just that, for all the packages in the project.

So: projects do not get installed, but packages do. Packages are
registered with a `package` stanza in the `dune-project` file.
Libraries to be published/installed in the package are registered by
using the `public_name` field of the `library` stanza of a `dune`
file; the name must match then name of the `package`, or its first
segment must match. Evidently a `package` stanza without any
corresponding library stanzas would not publish/install anything. But
what about a library with a `public_name` and no `package` stanza or
`dune-project` file?

If follows that one does not depend on a project but on packages, or
rather libraries in packages. That is, _source code_ does not depend
on projects; but the project containing the source does depend on
projects, to obtain their packages. So its a meta-dependency. If your
project depends on, say, angstrom, then you must install the angstrom
package in opam, and that opam package corresponds to dune-project.
That is, it's an opam package, but the opam file's build recipe
uses dune, which ...

But how does opam know which opam package to use? In the case of
angstrom, there are four opam files to choose from. And there are four
corresponding opam "packages" in the opam repository; each uses a copy
of the dune project. (e.g. `angstrom.0.15.0`, `angstrom-async.0.15.0`,
etc.). So evidently opam uses the file system location of the opam
files to decide which one to choose. The dune project contains all the
sources and the four opam files; but the opam files are installed in
opam-repository not as <pkg>.opam, but as <pkg>/opam. And that <pkg>
directory contains only the opam file (`<pkg>.opam` renamed `opam`).
All four opam files reference the same source tarball. So when opam is
asked to install one of them, it downloads and unpacks the tarball,
then uses the directory name to decide which of the opam files in the
sources to use to control the build: the directory name <pkg> must
match the prefix of an opam file <pkg>.opam, and it must also match
the `public_name` of a dune library somewhere in the source tree.
That's what dune will look for when the opam build recipe is executed:
the build instruction is `build -p <name>`, and opam is responsible
for expanding <name>, and it will use the directory name <pkg> for
this, telling dune to build the package with name <pkg>.

Egad. Could they not have made it a little more complex?

So then the question is, how can we translate this into the language
of OBazl?

To start, `public_name` corresponds cleanly to Bazel target name.

The tricky bit is dealing with workspaces. Each opam package should
treated as a Bazel workspace, getting its own WORKSPACE.bazel file.

Putting such opam workspaces into the deps env is simple; each
`public_name` library determines one workspace. Except that dune
projects may contain numerous such libraries that really make more
sense as packages within a single project-level workspace.

OTOH, anything listed in the `depends` field of an opam file must be
treated as a workspace, so that much is easy.

So for starters the rule is to make OPAM pkgs/deps distinct
workspaces; dune libraries with `public_name` do not become workspaces
unless they correspond to opam packages.

Method: maintain a workspaces env (a cache, table). To process an item
from an opam `depends` list, first check the cache. If not found, then
search the list of subdirs in the switch's .opam-switch/sources dir.
If not found, then it must not be installed, so run
`@opam//here/install -- -p <pkg>` to install it, then repeat. If
found, then create a new entry for the workspaces layer of the deps env.


link:https://dune.readthedocs.io/en/stable/concepts.html#package-specification[Dune Package specification,window="_blank"] -- "A package being a collection of executables, libraries and other files."

.dune-project
====
----
(package
 (name mypackage)
 (synopsis "My first Dune package!")
 (description "\| This is my first attempt at creating
              "\| a project with Dune.
))
----
====



[quote, 'link:https://dune.readthedocs.io/en/stable/concepts.html#declaring-a-package-1[Declaring a Package,window="_blank"]']
____
Once you have done this, Dune will know about the package named mypackage and you will be able to attach various elements to it. The package stanza accepts more fields, such as dependencies.

Note that package names are in a global namespace so the name you
choose must be universally unique....

In older projects using Dune, packages were defined by manually writing a file called <package-name>.opam at the root of the project. However, it is not recommended to use this method in new projects as we expect to deprecate it in the future. The right way to define a package is with a package stanza in the dune-project file."
____

"Attaching" stuff to a package:

[quote, 'link:https://dune.readthedocs.io/en/stable/concepts.html#libraries[Libraries,window="_blank"]']
____
In order to attach a library to a package all you need to do is add a public_name field to your library. This is the name that external users of your libraries must use in order to refer to it. Dune requires that the public name of a library is either the name of the package it is part of or start with the package name followed by a dot character.

For instance:

[source,lisp]
----
(library
 (name mylib)
 (public_name mypackage.mylib))
----

After you have added a public name to a library, Dune will know to install it as part of the package it is attached to. Dune installs the library files in a directory
----
<prefix>/lib/<package-name> <1>
----
____
<1> Here `<prefix>` will (usually) be the OPAM prefix (printed by `$ opam var prefix`), which defaults to `$HOME/.opam/<switch>`.


==== opam workspaces

Workspaces for an opam package are determined by the opam pkg name and
the dunefile that defines the corresponding library. ?

For example, `angstrom.opam` is in the root dir of `angstrom.0.15.0`,
and the library with `public_name` `angstrom` is defined in
`lib/dune`. So the angstrom workspace needs to be defined by
`lib/WORKSPACE.bazel`, not `./WORKSPACE.bazel`. If we did the latter,
we would have to use label `@angstrom//lib:angstrom` instead of
`@angstrom//:angstrom`.

This corresponds to how it gets installed in SWITCH/lib/angstrom.
Evidently when opam runs the dune build command, it includes
installation of th the _package_, and `public_name` determines the
name of the (library) package.

But does this mean that we need one workspace per dune library `public_name`?
