= File Generation
:page-permalink: /:path/filegen
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: ug
:page-sidebar: rules_ocaml_ug_sbdata
:page-parent: ['../user-guide']
:page-tags: [files,generation]
:page-last_updated: May 4, 2022
:page-toc: false

Generating files is easy in Bazel. No Obazl-specific rules are needed
to generate files and integrate them into your OCaml build. There are
two techniques you can use: link:#genrule[genrule] and a custom link:#template[template rule].

== genrule

Rule link:https://bazel.build/reference/be/general#genrule[genrule,window=_blank]
(for "general rule") provides a means of integrating
shell scripts into Bazel's hermitic build ecosystem. In addition to
passing the script via the `cmd` attribute, you must pass all inputs
(files and tools) and outputs, in accordance with the general Bazel
requirement. That's what allows Bazel to add your script to the
dependency graph, so as to ensure a reproducible build.

Example from link:https://github.com/obazl/dev_obazl/tree/main/demos/ppx/genrule[demos/ppx/genrule]:

```
genrule(
    name = "transform",
    srcs = ["hello.ml"],
    ## due to filename->module_name rules, output must be hello.ml, not e.g. hello.pp.ml
    outs = ["tmp/hello.ml"],
    tools = [":_ppx.exe"],
    ## $(location :_ppx.exe) resolves to wherever Bazel placed _ppx.exe.
    ## $< is the input file; $@ is the output file.
    cmd = "$(location :_ppx.exe) -dump-ast $< > $@"
)
```

This `genrule` runs a PPX executable (`:_ppx.exe`) to transform input
`hello.ml`, placing the output in `tmp/hello.ml`. The `":_ppx.exe"`
label refers to the `ppx_executable` target that produces the
executable; `$(location :ppx.exe)` is a Bazel-specific construct that
resolves to the file-system location of the file produced by
`:_ppx.exe` (which could be anywhere).

Emitting multiple files is a little more complicated. See the
link:https://bazel.build/reference/be/general#genrule[genrule documentation,window=_blank]
for more information.

IMPORTANT: To depend on a file produced by `genrule`, you can use
the label of the `outs` file.  You do not have to use the name of the rule.

== Custom template rules

Bazel supports a rudimentary templating functionality via the
link:https://bazel.build/rules/lib/actions#expand_template[expand_template,window=_blank]
action. To use this you must write a custom rule; fortunately that is
not terribly difficult to do. Describing how is beyond the scope of
this manual, but you can find a simple example with extensive comments at
link:https://github.com/obazl/dev_obazl/tree/main/demos/filegen/template[demos/filegen/template].
