= User Guide: rules_ocaml
:page-permalink: /:path/index.html
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: ug
:page-sidebar: rules_ocaml_ug_sbdata
:page-tags: [formatting]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: June 1, 2022
:toc: true

== The OBazl Ruleset(s)

Core collection of primitives (build rules) that can be composed to accomplish any build task.

The most basic build tasks are compilation of interface and
implementation files, linking of archive files, and linking of
executables. OBazl includes one rule for each of these tasks, named
accordingly: `ocaml_signature`, `ocaml_module`, `ocaml_archive`, and
`ocaml_executable`.

Most real-world projects involve some additional tasks:

* preprocessing of source files, including but not limited to PPX transformations;
* renaming of source files to add a namespace prefix;
* generation of a `resolver` module (sometimes called a "map" file)
  containing the module aliasing equations required to make
  namespacing ("wrapped" libraries in Dune) work.

None of these tasks involve the OCaml toolchain, so (following the
Principle of Parsimony), OBazl does not include rules for them. They
can all accomplished using the standard `genrule` ("general rule")
provided by Bazel.

Here is an example of a simple build pipeline using only OBazl
primitives, to compile a namespaced module with a PPX transformation:

```
source file -> genrule to rename src -> genrule to execute ppx transform -> ocaml_module
```

In this example, the first step would use a shell command (`cp` or
`ln`), and the second step, running a PPX transform, would depend on
the output of another pipeline ending in an `ocaml_executable` that
produces the PPX executable. Both `genrule` steps would involve a
shell command that must be written by the programmer.

In this case Bazel would function more or less as a glorified Make; it
would analyze dependencies and invoke the build actions required by a
change in sources, but would delegate actual build responsibility to
the shell scripts written in the genrules (except for the final
`ocaml_*` rule). So this is not something one would do in practice.
Nonetheless, in principle such composable pipelines could be used to
build any OCaml project. But build files written at such a low level
of detail would be tedious to write, error-prone (since they involve
shell scripting), verbose, and hard to maintain. So in order to meet
its design goals (Ease of Use, etc.), OBazl extends some of its rules
to automate the most common build patterns in a more convenient and
expressive manner, and to take advantage of the Bazel's specialized
build API. For example, instead of passing the PPX executable to a
genrule (which runs a shell command that the developer must write)
that runs it as a separate task, we can pass it directly to the
`ocaml_module` rule via its `ppx` attribute, which has the effect of
directing the rule to run the transform and compiles output. The
transform will still be executed as a separate build _action_, but it
will be managed by the `ocaml_module` rule, so the developer doesn't
have to bother directly with the details of a shell command. The OBazl
rules have also been extended to automate namespacing, so that the
developer is responsible only for annotating the rules with attributes
indicating namespace membership, and OBazl takes care of the rest.

NB: compositionality:  rules v. build actions

OBazl includes two rulesets:

* link:https://github.com/obazl/rules_ocaml/tree/5.0.0.alpha[rules_ocaml,window=_blank] (Version 5.0.0.alpha)
* link:https://github.com/obazl/rules_ppx/tree/5.0.0.alpha[rules_ppx,window=_blank] (Version 5.0.0.alpha)

// === rules_bootstrap

// The `bootstrap` ruleset is a special case. It is designed expressly
// and solely to support building the OCaml compiler. Building the
// compiler requires bootstrapping: the build rules cannot rely on an
// OCaml compiler to build the OCaml compiler. Instead they must first
// compile the bootstrapping compiler, which is written in C, and then
// use it to compile the OCaml sources and produce an OCaml compiler
// proper. The standard OBazl ruleset cannot be used to build the
// compiler, since it depends on an already-built compiler.

// The `bootstrap` ruleset uses a stripped-down version of the standard
// ruleset, and replaces the standard toolchain with a toolchain that
// uses the bootstrapping tools. The compiler code does not use PPX
// preprocessing, and uses only a single hand-coded namespace (the
// Stdlib), so it does not need support for general namespacing. So the
// bootstrap rules use the same code as the standard ruleset, except that
// everything not necessary to build the compiler is stripped out.
// Consequently the bootstrap rules are much simpler than the standard
// rules, and users interested in knowing how OBazl works should start by
// studying the bootstrap rules.

// Because the `bootstrap` ruleset is designed only to be used in
// building the compiler, it is not distributed with the OBazl package,
// nor is it independently downloadable. Instead it is included directly
// in the link:https://github.com/obazl-repository/ocaml[OBazl fork of the compiler].

=== rules_ocaml

The standard `rules_ocaml` ruleset can be thought of as a layer
that sits on top of and extends the bootstrap ruleset. All the added
functionality could be implemented using generic Bazel facilities
(genrules, macros, custom rules), but OBazl provides built-in support
for the most commonly needed to ensure ease-of-use etc.

NOTE: The point being that Bazel (Starlark) is the build language,
OBazl just uses it to define rules that make life easier, and the
programmer always has access to the full power Bazel. I.e. you're not
limited in to the functionality OBazl supports out-of-the-box. Contrast
Dune, which does not build on a lower-level build DSL in this way.


It adds support for:

* PPX processing, including automated management of so-called "runtime dependencies"

* Generalized namespacing (automatic generation of "ns resolver"
  modules) to compliment the automatic module renaming supported by
  the bootstrap rules.

* Contingent dependencies - selection of dependencies based on configuration state
  ** corresponds to Dune's "alternative dependencies" using `(select ... from ...)`
  ** no special syntax or functionality is involved; dependencies may
     be selected using Bazel's standard, generic `select` function
  ** NB: this is just a matter of using Bazel's `select` function for deps, so it is available in the bootstrap ruleset.

* Full control over module bindings
  ** A module rule can select any implementation file for binding to
     any particular signature (.cmi) file, based on configuration
     settings; for example, binding `clock.cmi` to a platform-specific
     implementation e.g. `clock_linux.ml` is expressible using a
     simple `select` statement on a single `ocaml_module` target.
  ** Eliminates need for
     link:https://dune.readthedocs.io/en/stable/variants.html?highlight=virtual%20modules#virtual-library["virtual
     libraries"]. Module bindings like this need not be delayed to
     link-time.


== Dev tasks

* Compile a signature
* Compile a module
* Define a namespace library
* Assemble a library
* Archive a library
* Link an executable
* Link custom executable variants: `-custom`, `-output-complete-exe`, etc.
* Build a custom runtime (`-make-runtime`)
* Link CC code to OCaml code


== Additional Topics

* link:https://bazel.build/run/build#build-phases[Bazel build phases,window=_blank]
* link:https://docs.bazel.build/versions/master/skylark/concepts.html#evaluation-model[Bazel evaluation model,window=_blank]
* link:https://bazel.build/external/advanced#offline_builds[Offline builds,window=_blank]
* link:https://github.com/bazel-contrib/rules_oci[Containerization,window=_blank] (Docker, OCI, etc.)
* Continuous Integration
** link:https://blog.bazel.build/2016/01/27/continuous-integration.html[Using Bazel in a continuous integration system] - Bazel blog article (2016)
** link:https://www.wix.engineering/post/continuous-integration-on-a-mammoth-scale-using-bazel[Continuous Integration on a Huge Scale Using Bazel] - WiX Engineering
** link:https://buildkite.com/docs/tutorials/bazel[Using Bazel on Buildkite]
* link:https://docs.bazel.build/versions/master/persistent-workers.html[Persistent workers]
* link:https://docs.bazel.build/versions/master/remote-caching.html[Remote caching]
* link:https://docs.bazel.build/versions/master/remote-execution.html[Remote execution]
* link:https://docs.bazel.build/versions/master/platforms.html[Platforms] - cross-platform development
