= Profiles
:page-permalink: rules-ocaml/user-guide/profiles
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: ug
:page-tags: [profiles]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: May 2, 2022
:page-toc: true
:toc: true



== Configuration groups

A Configuration Profile (or "group") is a collection of build options and
configuration rules. You can define such profiles by tagging
command-line options in your `.bazelrc` or `user.bazelrc` file and
activate them using the `--config` option.

Build options control Bazel itself; configuration rules are defined by
the user and control the (Starlark) build program that executes within
the Bazel environment.

For example:

[.bazelrc]
```
## build options
build:show --subcommands
build:show --verbose_failures
build:showpp --subcommands=pretty_print
build:showpp --verbose_failures
```

This defines configuration profiles that can be activated by passing
`--config=show` or `--config=showpp`.

You can make these available to all Bazel projects by putting the directives in `$HOME/.bazelrc`.


Documentation on build options and `--config` are buried at the bottom
of
link:https://docs.bazel.build/versions/master/guide.html#bazelrc-syntax-and-semantics[.bazelrc
syntax and semantics].

== Build profiles

Implemented as toolchains...

