---
// layout: rules_ocaml_ug
title: Changelog
permalink: /changelog
tags: [changes]
keywords: notes, tips, cautions, warnings, admonitions
last_updated: April 21, 2022
sidebar: false
toc: false
---


= OBazl toolsuite Changelog

== Version 3:

=== Breaking Changes

* https://github.com/obazl/coswitch[coswitch] has been replaced by https://github.com/obazl/tools_opam[tools_opam].
** opam package labels have changed. The Bazel label for any opam package has prefix `opam.` (this can be changed; see the `tools_opam` documentation), and the library itself is in Bazel package `//lib`; for example, `@opam.ounit2//lib`. Subpackages are named similarly, e.g. `@opam.mtime//clock/os/lib`.
* `ocaml_archive` and `ocaml_ns_archive` have been removed. Use `ocaml_library` instead.

* https://github.com/obazl/tools_ocaml[tools_ocaml] has been replaced; see <<_new-rulesets>> below.
* Minimum Bazel version is 8.

=== Non-breaking changes

* `ocaml_ns` is now a macro
* Attribute `cc_deps` on `ocaml_module` sets compilation_mode to opt
* Much code refactoring and cleanup
* More documentation

=== New rules

* `ocaml_ns_config` - generated by macro `ocaml_ns`
* `ocaml_ns_module` - generated by macro `ocaml_ns`
* `ocaml_runtime` - support for `-make-runtime`, `-with-runtime`

=== New rulesets

* ppx support has been migrated to https://github.com/obazl/rules_ppx[rules_ppx]
* menhir support has been migrated to https://github.com/obazl/rules_menhir[rules_menhir]
* https://github.com/obazl/rules_ctypes[rules_ctypes] - support for https://github.com/yallop/ocaml-ctypes[ocaml-ctypes] package.
* https://github.com/obazl/rules_cppo[rules_cppo] - support for the https://github.com/ocaml-community/cppo[cppo] tool

=== New tools

Support added for the tools in the standard SDK (`ocamldebug`, `ocamlobjinfo`, etc.) and for a subset of the OCaml Platform tools (`opam`, `utop`, `ppxlib`).

=== Deprecations
* `ocaml_ns_library` is deprecated and will be removed in the next version.

== Version 2:

=== Breaking Changes

* The tool for OPAM integration is https://github.com/obazl/coswitch[coswitch]

* renaming
  ** `ocaml_module` attributes `src` and `intf` renamed to `struct` and `sig`, respectively
  ** `modules` attribute of `ocaml_library` renamed to `manifest`
  ** rule `ocaml_interface` renamed to `ocaml_signature`
  ** `deps_adjunct` renamed to `ppx_codeps` (i.e. co-dependencies)
  ** OPAM package labels have changed. See link:https://github.com/obazl/coswitch[coswitch] for more information.
  example, `ppx_deriving.eq -> @ppx_deriving//eq`, `mtime.clock.os ->
  @mtime//clock/os`. To make these targets available the new
  link:/tools-opam/user-guide[OPAM bootstrapper tool,window=_blank]
  must be run separately.
* namespacing support has been thoroughly revised, see below for details

* deletions
  ** attribute `deps_opam` removed; opam deps are no longer special, and are treated like any other dep
  ** attribute `deps_adjunct_opam` removed

=== Non-breaking changes

* Rule `ocaml_archive` is deprecated and will be removed in a future version. Use instead `ocaml_library` with attribute `archived=True`.

* Rule `ocaml_ns_archive` is deprecated and will be removed in a future version. Use instead `ocaml_ns_library` with attribute `archived=True`.

* Toolchain support has changed drastically, but this should not
effect existing code, except insofar as OPAM dependencies must be
changed as noted above. For example version 1 generated build commands
that used `ocamlfind`, which it assumed to be installed in OPAM.
Version 2 does not use `ocamlfind`; the commands it generates invoke
the OCaml compilers directly, via the toolchain interface. This change
should not affect existing build code.

=== New stuff

* The new link:https://github.com/obazl/coswitch[coswitch] tool generates code implementing OPAM-integrated toolchains.

* bottom-up namespacing

* toolchain independence

* cc deps produced by `cc_*` rules (e.g. `cc_library`) may be added directly to the `deps` attribute of `ocaml_module`
* new rules:
  ** link:/rules-ocaml/reference/ocaml-rules#_ocaml_lex[ocaml_lex]
  ** link:/rules-ocaml/reference/ocaml-rules#_ocaml_ns_resolver[ocaml_ns_resolver]
  ** link:/rules-ocaml/reference/ocaml-rules#_ocaml_yacc[ocaml_yacc]
  ** link:/rules-ocaml/reference/ocaml-rules#_ocaml_test[ocaml_test]

* Rules for third-party tools (e.g. menhir) are in link:https://github.com/obazl/tools_ocaml[tools_ocaml]
