= The OBazl Book
:page-permalink: /
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: home
:page-sidebar: rules_ocaml_home_sbdata
:page-tags: [bazel]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Mar 27, 2025
:page-toc: true
:toc: true

This site documents the OBazl toolsuite, version 3.0.0.

[WARNING]
====
Version 3.0.0.beta.1 scheduled for release on Mar 28, 2025 or thereabouts.

This documentation is a Work-In-Progress. Things will be a little
messy and incomplete. The best way to learn how to use the rules is
probably to find some relevant link:#Demos[demos].
====

* link:changelog[CHANGES] from previous versions.
* link:status[Status]

== Getting started

The easiest way to get started is to fork/clone one of the demo projects, but
you can also use the `@obazl//new` tool to generate a project from a template.

=== Demo projects

NOTE: The demo projects use the `xdg` opam toolchain strategy
(explained in link:tools-opam/user-guide[tools-opam]); this means the initial build will create an opam root
and switch in `$XDG_DATA_HOME`. This only happens once, and `xdg`
toolchains are shared by all OBazl projects. So the initial build may
take a while; thereafter builds should be reasonably fast.

.demo_hello
[%collapsible%open]
====
----
$ git clone https://github.com/obazl/demo_hello.git
$ cd demo_hello
$ bazel run bin:hello
$ bazel test test
$ bazel build //...                         <1>
$ bazel test //...                          <2>
$ bazel test //... --build_tests_only       <3>
----
<1>  Builds all targets
<2>  Builds all targets and runs all tests
<3>  Runs all tests but only builds targets required by the tests
====

Other demos:

* https://github.com/obazl/demos_obazl[demos_obazl,window=_blank] contains over 150 small demos in the https://github.com/obazl/demos_obazl/tree/main/rules_ocaml[rules_ocaml,window=_blank] subdirectory. 
* https://github.com/obazl/demos_ctypes[demos_ctypes] contains two examples demonstrating the use of https://github.com/obazl/rules_ctypes[rules_ctypes], an OBazl extension supporting https://github.com/yallop/ocaml-ctypes[ocaml-ctypes].  Also demonstrates integration of OCaml and C using https://github.com/bazelbuild/rules_cc[rules_cc].

=== `@obazl//new`: generating a new project



.Generate a new project
[%collapsible%open]
====
----
$ mkdir obazl && cd obazl
$ cat > .bazelrc <<EOF
common --registry=https://raw.githubusercontent.com/obazl/registry/main/
common --registry=https://bcr.bazel.build
EOF
$ cat > MODULE.bazel <<EOF
module(name="myproj")
bazel_dep(name = "tools_obazl", version = "3.0.0", repo_name = "obazl")
EOF
$ bazel run @obazl//new -- --help
$ bazel run @obazl//new -- --list
Templates available from library @templates_ocaml
	ffi/ctypes
		Minimal project using ctypes library
        ...
	proj/hello
		Minimal working example
...
$ bazel run @obazl//new -- -t proj/hello -n howdy
$ cd howdy
$ bazel build //... --show_result=10            <1>
$ bazel test //... --show_result=10
----
<1> Builds all targets.  `--show_result` is optional; it tells OBazl to tell print information about build outputs, which is not printed by default.
====


== Support
* Discord: link:https://discord.gg/PHSAW5DUva[OBazl,window=_blank]

* Bluesky: https://bsky.app/profile/obazl.bsky.social[obazl.bsky.social,window=_blank]

=== Acknowledgements

Support for the development of OBazl was provided by a Mina Genesis
Token Grant and the generous assistance of the link:https://minaprotocol.com[Mina,window=_blank] team. Additional support provided by link:https://www.tweag.io[Tweag,window=_blank]
