= The OBazl Book
:page-permalink: /
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: home
:page-sidebar: rules_ocaml_home_sbdata
:page-tags: [bazel]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Mar 31, 2025
:page-toc: true
:toc: true

This site documents the OBazl toolsuite, version 3.0.0.beta.1

[WARNING]
====

This documentation is a Work-In-Progress. Things will be a little
messy and incomplete. The best way to learn how to use the rules is
probably to find some relevant link:#Demos[demos].
====

* link:changelog[CHANGES] from previous versions.
* link:status[Status]

== Getting started

The easiest way to get started is to fork/clone one of the demo projects, but
you can also use the `@obazl//new` tool to generate a project from a template.

=== Demo projects

NOTE: The demo projects use the `xdg` opam toolchain strategy
(explained in https://github.com/obazl/tools_opam[tools-opam,window=_blank]); this means the initial build will create an opam root
and switch in `$XDG_DATA_HOME`. This only happens once, and `xdg`
toolchains are shared by all OBazl projects. So the initial build may
take a while; thereafter builds should be reasonably fast.

.demo_hello
[%collapsible%open]
====
----
$ git clone https://github.com/obazl/demo_hello.git
$ cd demo_hello
$ bazel run bin:greetings
$ bazel run bin:greetings --tc=ocamlc              <0>
$ bazel test test
$ bazel run @opam                                  <1>
$ bazel clean                                      <2>
$ bazel build //...                                <3>
$ bazel test //...                                 <4>
$ bazel test //... --build_tests_only              <5>

$ bazel build lib/hello:Hello --config=modinfo     <6>
$ bazel build lib/hello:Hello --config=modinfo --tc=ocamlc
$ bazel build lib/hello:Hello --config=siginfo     <7>
$ bazel build lib/hello:Hello --config=cmtinfo     <8>
$ bazel build lib/hello:Hello --config=cmtiinfo    <9>
$ bazel build lib/goodbye:Goodbye --config=gensig  <10>

$ bazel run @ocaml
$ bazel run @utop
$ bazel run @dbg --pgm=bin:greetings               <11>

$ dune build                                       <12>
$ dune run bin/main.exe                            <13>
$ dune test

----
<0> Uses `ocamlc.opt` compiler.  `--tc=<compiler>` can be used with all cmds here.
<1> Runs opam; shows location of switch.
<2>  Forces rebuild. Rarely needed in practice.
<3>  Builds all targets
<4>  Builds all targets and runs all tests
<5>  Runs all tests but only builds targets required by the tests
<6> Runs `ocamlobjinfo` against hello.cmx (see .bazelrc)
<7> Runs `ocamlobjinfo` against hello.cmi (see .bazelrc)
<8> Runs `ocamlcmt` against hello.cmt (see .bazelrc)
<9> Runs `ocamlcmt` against hello.cmti (see .bazelrc)
<10> Generate interface for goodbye.ml (`ocamlc -i`) (see .bazelrc)
<11> Runs `ocamldebug`. See .bazelrc
<12> Dune and Bazel play nice together.
<13> Dune requires that the executable name match a module name.
====

Other demos:

* https://github.com/obazl/demos_obazl[demos_obazl,window=_blank] contains over 150 small demos in the https://github.com/obazl/demos_obazl/tree/main/rules_ocaml[rules_ocaml,window=_blank] subdirectory. 
* https://github.com/obazl/demos_ctypes[demos_ctypes] contains two examples demonstrating the use of https://github.com/obazl/rules_ctypes[rules_ctypes], an OBazl extension supporting https://github.com/yallop/ocaml-ctypes[ocaml-ctypes].  Also demonstrates integration of OCaml and C using https://github.com/bazelbuild/rules_cc[rules_cc].

=== `@obazl//new`: generating a new project



.Generate a new project
[%collapsible%open]
====
----
$ mkdir obazl && cd obazl
$ cat > .bazelrc <<EOF
common --registry=https://raw.githubusercontent.com/obazl/registry/main/
common --registry=https://bcr.bazel.build
EOF
$ cat > MODULE.bazel <<EOF
module(name="myproj")
bazel_dep(name = "tools_obazl", version = "3.0.0", repo_name = "obazl")
EOF
$ bazel run @obazl//new -- --help
$ bazel run @obazl//new -- --list
Templates available from library @templates_ocaml
	ffi/ctypes
		Minimal project using ctypes library
        ...
	proj/hello
		Minimal working example
...
$ bazel run @obazl//new -- -t proj/hello -n howdy
$ cd howdy
$ bazel build //... --show_result=10            <1>
$ bazel test //... --show_result=10
----
<1> Builds all targets.  `--show_result` is optional; it tells OBazl to tell print information about build outputs, which is not printed by default.
====


== Support
* Discord: link:https://discord.gg/PHSAW5DUva[OBazl,window=_blank]

* Bluesky: https://bsky.app/profile/obazl.bsky.social[obazl.bsky.social,window=_blank]

=== Acknowledgements

Support for the development of OBazl was provided by a Mina Genesis
Token Grant and the generous assistance of the link:https://minaprotocol.com[Mina,window=_blank] team. Additional support provided by link:https://www.tweag.io[Tweag,window=_blank]
