= Namespacing support
:page-permalink: /:path/obazl_namespacing
:page-layout: page_rules_ocaml
:page-pkg: rules_ocaml
:page-doc: dg
:page-parent: ['../dev-guide']
:page-sidebar: rules_ocaml_dg_sbdata
:page-tags: [formatting]
:page-keywords: notes, tips, cautions, warnings, admonitions
:page-last_updated: Feb 11, 2025
:toc: true

== Terminology

NS resolver module - a module containing module aliasing equations; “ns-resolver” for short.

NS library - collection of modules aliased by an ns-resolver module.
Not necessarily archived or even aggregated as `ocaml_library`.

NS - namespace determined by the name of an ns-resolver. Note that
every module name determines a namespace; OBazl uses “ns” and
“namespace” specifically to refer to namespaces determined by ns-resolver modules.

https://ocaml.org/manual/5.3/names.html#module-path[module-path] -
Segmented module name like `A.B.C`; defined by the language. Has no
relation to file system directory paths.

ns-submodule - a module in an ns-lib, accessible using the OCaml
module path formed from the ns name, e.g. `Foo.A` is an ns-submodule
in ns `Foo`.

ns-qualified module name: name with ns prefix. ns-qualified names
emulate filesystem-based namespacing. For example, `foo__A.ml` emulates `foo/a.ml`.

resolved ns-submodule name - the RHS of an aliasing equation. E.g.
given `+module A = Foo__A+`, the resolved ns name of ns-submodule
`Foo.A` is `+Foo__A+` (ns-qualified). Given `+module A = B+`, the resolved
ns name is `B` (unqualified)

An ns-lib may contain ns-submodules that are not ns-qualified.



== Defining a namespace library: `ocaml_ns`

The `+ocaml_ns+` rule defines a namespace.

[source="starlark"]
----
ocaml_ns(
    name = "nsFoo",
    ns   = "foo",
    manifest = [":A", ...],
    ...
)
----


* This defines a filesystem prefix by suffixing `+__+` to the value of
  the `ns` attribute. For example, if `+ns = "foo"+`, then the prefix
  will be `+foo__+`. The filesystem prefix will be used to construct
  the filenames (and thus module names) of the ns-submodules listed in
  the `manifest` list.
* It generates a file containing module aliasing equations for the
  modules listed in the `manifest` attribute. In this example, `+module
  A = Foo__A+`. The module prefix `+Foo__+` is formed by capitalizing
  the first character of the filesystem prefix.
* It passes the filesystem prefix on to clients in its provider
  (`OCamlNsResolverProvider`) as `+fs_prefix+`. Clients use this to
  construct namespaced filenames.

Modules register their membership in the namespace by using it in the
`ns` attribute. For example:

[source="starlark"]
----
ocaml_module(
    name          = "A",
    ns            = ":nsFoo",        <1>
    struct        = "a.ml",
    ...
)
----
<1> Here `:nsFoo` is the label of the `+ocaml_ns+` build target; it is
not the namespace name.

In this example, the `+ocaml_ns+` build target generates an
ns-resolver module and passes its ns_prefix (`+foo__+`) to this client
target , so it will compile `a.ml` to `+foo__A.cmi+` and
`+foo__A.cma+`.

Clients that want to use the namespace can list it in either the
`deps` or the `open` attribute.

=== NS aliasing

With the `+ns_aliases+` attribute you can include other namespaces as
components of your namespace under new names. For example, suppose

           //ns/bottomup/embed/colors/rgb:nsRGB

is a namespace whose name is `Rgb`, with ns-submodules `Rgb.Red`,
`Rgb.Green`, and `Rgb.Blue`. You can make this available within
namespace `Foo` like so:

[source="starlark"]
----
ocaml_ns(
    name = "nsFoo",
    ns   = "foo",
    visibility = ["//visibility:public"],
    ns_aliases = {"//ns/bottomup/embed/colors/rgb:nsRGB": "RGB"}
)
----

This aliases `+Foo.RGB.Red+` to `+Rgb.Red+` etc.

The implementation is simple. The `+ns_aliases+` attribute has type
`+label_keyed_string_dict+`, which means they keys are labels and the
values are strings. Since the keys are labels of `+ocaml_ns+` targets,
the rule implementation can extract the original namespace name, and use it and the string values to construct aliases, e.g.

    module RGB = Rgb

And since the keys are dependencies, the rule implementation can
ensure that they are listed as inputs to any compile/link actions.

For an example see https://github.com/obazl/demos_obazl/tree/main/rules_ocaml/ns/bottomup/ns_aliases.

=== Include

=== Open

=== Hierarchy

== Private namespaces

Private namespaces are visible and accessible only to targets within
the same Bazel package.

To make a namespace private, set the `visibility` attribute of
`+ocaml_ns+` to private:

[source="starlark"]
----
ocaml_ns(
    name = "nsRe",
    ns   = "re",
    visibility = ["//visibility:private"],
    ...
)
----

The namespace resolver module file generated by this target will be
named `+re__.ml+`, and any ns-submodule `A` in this namespace will
named `+re__A.ml+` . The trailing `+__+` in the resolver module name
is intended to prevent name clashes, in case the Bazel package also
contains a module file with the same name as the namespace (e.g.
`re.ml`).

If the visibility were set to anything other than private, then the
resolver module file would be named `re.ml` (without the trailing
`+__+`), but the ns-submodules in the namespace would still be renamed
with the same prefix (`+re__+`).

If `re.ml` depends on (the ns-submodules in) the namespace, use the
`open` attribute:

[source="starlark"]
----
ocaml_module(
    name   = "Re",
    struct = "re.ml",
    open   = [":nsRe"],        <1>
    ...
)
----
<1> Since `nsRe` is the label of the private `ocaml_ns` target, which
produces ns resolver module `+re__.ml+`, this will translate into
command line option `+-open Re__+`.

An alternative strategy for handling the case where you have a module
with the same name as the ns is to give the namespace a completely
different name (meaning the `ns` attribute, not the `name` attribute). For example:

[source="starlark"]
----
ocaml_ns(
    name = "nsRe",
    ns   = "nsre",
    visibility = ["//visibility:public"],
    ...
)
----

This would generate resolver module `nsre.ml`, and ns-submodule prefix
`+nsre__+`. The `re.ml` module declared above will work unchanged,
since in this case `open = [":nsRe"]`
will translate to `+-open
Nsre+`.
